### ISSUE TITLE
The Persistance example does not work...

### ISSUE THREAD

**Issue by njoannin** [elasticsearch/elasticsearch-dsl-py#66]
Hello,

I've just started looking at using DocType for my project but ran into some errors.
I then just copy/pasted to a file the persistance example from the readme file and obtained the same results when I ran it...

The output I got was:

    Nicolass-MacBook-Pro: Nicolas$ python testing_doc_type.py 
    Traceback (most recent call last):
      File "testing_doc_type.py", line 6, in <module>
        connections.add_connection(Elasticsearch())
    AttributeError: 'module' object has no attribute 'add_connection'

I tried modifying the connections line so as to read:

    connections.connections.add_connection(Elasticsearch())

But that resulted in the following error:

    Nicolass-MacBook-Pro: Nicolas$ python testing_doc_type.py 
    Traceback (most recent call last):
      File "testing_doc_type.py", line 6, in <module>
        connections.connections.add_connection(Elasticsearch())
    TypeError: add_connection() missing 1 required positional argument: 'conn'

Looking at the Connections class, I am not sur what I should put in as "alias" (since Elasticsearch() should be "conn", right?).

I'm probably missing something basic here... Any help (and update to the readme file) would be greatly appreciated!

Nicolas

Using Python 3.3, elasticsearch-py 1.3.0, elasticsearch-dsl-py 0.0.3

**Comment by njoannin** [comment]
Playing around with it: I tried adding a string to serve as alias. I put in "alias1".
That threw:

    KeyError: "There is no connection with alias 'default'."

I then changed "alias1" to "default", and then the file would run.
